### ISSUE TITLE
Cannot run in browser- `path` module not found error

### ISSUE THREAD

**Issue by abose** [UziTech/eslint-linter-browserify#426]
Hi,

 I am trying to integrate this into https://phcode.dev and i am unable to run the simple code i copy pasted from the readme below. It looks like the `path` module is not there for some reason. What am i doing wrong?
Any help is much appreciated. Thanks!

```html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Title</title>
        <script src="https://cdn.jsdelivr.net/npm/eslint-linter-browserify/linter.js"></script>
        <script type="module">
            const linter = new eslint.Linter();

            const messages = linter.verify(
                "var foo;",
                {
                    rules: {
                        semi: ["error", "never"]
                    }
                },
                { filename: "foo.js" }
            );
        </script>
    </head>
    <body></body>
</html>

```

## the error
```console
linter.js:117169 Uncaught TypeError: Cannot read properties of undefined (reading 'sep')
    at normalizeFilename (linter.js:117169:41)
    at normalizeVerifyOptions (linter.js:117213:21)
    at Linter._verifyWithFlatConfigArrayAndWithoutProcessors (linter.js:118128:27)
    at Linter._verifyWithFlatConfigArray (linter.js:118524:23)
    at Linter.verify (linter.js:118013:63)
    at a.html:11:37
```

![image](https://github.com/UziTech/eslint-linter-browserify/assets/5336369/1aee2f33-7fef-4dd2-a34f-abd165d88e1a)

**Comment by UziTech** [comment]
Looks like this is an issue in v9.3.0 with node polyfills

v9.2.0 works

```html
<script src="https://cdn.jsdelivr.net/npm/eslint-linter-browserify@9.2.0/linter.js"></script>
```

I'll try to see what I can do to fix it in v9.3.0

**Comment by UziTech** [comment]
This will be fixed in the next release

**Comment by abose** [comment]
Thanks for fixing quickly 😄
